# Generated by Django 4.2.11 on 2024-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
