# Generated by Django 4.2.11 on 2024-05-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0002_game_game_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
