# Generated by Django 4.2.11 on 2024-05-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0005_ball_paddle_remove_game_player1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Paddle',
        ),
    ]
