# Generated by Django 4.2.11 on 2024-05-17 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_service', '0006_delete_ball_delete_game_delete_paddle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament', max_length=30)),
                ('nb_player', models.IntegerField()),
                ('nb_round', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='participating_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
