# Generated by Django 4.2.11 on 2024-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0008_alter_tournament_creator_alter_tournament_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
