# Generated by Django 4.2.11 on 2024-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0009_tournament_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='nb_player_direct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_player',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_round',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
