# Generated by Django 4.2.11 on 2024-05-22 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_service', '0010_tournament_nb_player_direct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(related_name='participating_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
