# Generated by Django 4.2.11 on 2024-05-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0034_alter_profil_status'),
        ('game_service', '0011_alter_tournament_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to='auth_service.profil'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(related_name='participating_tournaments', to='auth_service.profil'),
        ),
    ]
