# Generated by Django 4.2.11 on 2024-05-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0034_alter_profil_status'),
        ('game_service', '0012_alter_tournament_creator_alter_tournament_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curent_user', to='auth_service.profil'),
        ),
    ]
