# Generated by Django 4.2.11 on 2024-05-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0013_tournament_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
    ]
