# Generated by Django 4.2.11 on 2024-05-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0036_remove_profil_channel_name'),
        ('game_service', '0014_remove_tournament_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='nb_round',
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='auth_service.profil')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='auth_service.profil')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_service.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='auth_service.profil')),
            ],
        ),
    ]
