# Generated by Django 4.2.11 on 2024-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0015_remove_tournament_nb_round_tournament_round_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches_created',
            field=models.BooleanField(default=False),
        ),
    ]
