# Generated by Django 4.2.11 on 2024-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0016_tournament_matches_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
