# Generated by Django 4.2.11 on 2024-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0018_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
