# Generated by Django 4.2.11 on 2024-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0019_tournament_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='nb_round',
            field=models.IntegerField(default=0),
        ),
    ]
