# Generated by Django 4.2.11 on 2024-05-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0038_merge_20240524_1158'),
        ('game_service', '0020_match_nb_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='survivor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor_tournaments', to='auth_service.profil'),
        ),
    ]
