# Generated by Django 4.2.11 on 2024-06-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0041_merge_20240603_1358'),
        ('game_service', '0021_tournament_survivor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_tournaments', to='auth_service.profil'),
        ),
    ]
