# Generated by Django 4.2.11 on 2024-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0021_tournament_survivor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCLI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_left_y', models.FloatField(default=0.5)),
                ('paddle_right_y', models.FloatField(default=0.5)),
                ('ball_x', models.FloatField(default=0.5)),
                ('ball_y', models.FloatField(default=0.5)),
                ('ball_vx', models.FloatField(default=0.01)),
                ('ball_vy', models.FloatField(default=0.01)),
                ('score_left', models.IntegerField(default=0)),
                ('score_right', models.IntegerField(default=0)),
            ],
        ),
    ]
