# Generated by Django 4.2.11 on 2024-06-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0023_match_loser_match_score_loser_match_score_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_service.tournament'),
        ),
    ]
