# Generated by Django 4.2.11 on 2024-06-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0022_gamecli'),
        ('game_service', '0024_alter_match_tournament'),
    ]

    operations = [
    ]
