# Generated by Django 4.2.11 on 2024-06-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0047_delete_finishedgame'),
        ('game_service', '0025_merge_0022_gamecli_0024_alter_match_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('draw', models.BooleanField(default=False)),
                ('give_up', models.BooleanField(default=False)),
                ('pts_player1', models.IntegerField(default=0)),
                ('pts_player2', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='auth_service.profil')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='auth_service.profil')),
            ],
        ),
    ]
