# Generated by Django 4.2.11 on 2024-06-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0026_finishedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgame',
            name='loser_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishedgame',
            name='winner_points',
            field=models.IntegerField(default=0),
        ),
    ]
