# Generated by Django 4.2.11 on 2024-06-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0027_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_timer_running',
            field=models.BooleanField(default=False),
        ),
    ]
