# Generated by Django 4.2.11 on 2024-06-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0028_tournament_is_timer_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_timer_running',
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
