# Generated by Django 4.2.11 on 2024-06-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0029_remove_tournament_is_timer_running_delete_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='timer_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='game_service.timermanager'),
        ),
    ]
