# Generated by Django 4.2.11 on 2024-06-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0030_timermanager_tournament_timer_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='timer_manager',
        ),
    ]
