# Generated by Django 4.2.11 on 2024-06-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0031_remove_tournament_timer_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerManager',
        ),
    ]
