# Generated by Django 4.2.11 on 2024-06-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0027_finishedgame_loser_points_finishedgame_winner_points'),
        ('game_service', '0032_delete_timermanager'),
    ]

    operations = [
    ]
