# Generated by Django 4.2.11 on 2024-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0032_delete_timermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=15),
        ),
    ]
