# Generated by Django 4.2.11 on 2024-06-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0033_alter_tournament_name'),
        ('game_service', '0033_merge_20240628_1124'),
    ]

    operations = [
    ]
