# Generated by Django 4.2.11 on 2024-04-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_customuser_date_joined_customuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
