# Generated by Django 4.2.11 on 2024-04-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
