# Generated by Django 4.2.11 on 2024-04-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
    ]
