# Generated by Django 4.2.11 on 2024-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0012_alter_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='session_id',
            field=models.TextField(default=''),
        ),
    ]
