# Generated by Django 4.2.11 on 2024-04-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0013_profil_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='session_id',
        ),
    ]
