# Generated by Django 4.2.11 on 2024-04-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0014_remove_profil_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
