# Generated by Django 4.2.11 on 2024-04-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_service', '0016_alter_profil_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='id',
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
