# Generated by Django 4.2.11 on 2024-04-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0021_alter_profil_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='avatar',
        ),
    ]
