# Generated by Django 4.2.11 on 2024-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0023_profil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='avatar_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
