# Generated by Django 4.2.11 on 2024-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0025_remove_profil_avatar_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('in_game', 'Playiiing')], default='inactive', max_length=20),
        ),
    ]
