# Generated by Django 4.2.11 on 2024-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0026_alter_profil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('in_game', 'Playing')], default='active', max_length=20),
        ),
    ]
