# Generated by Django 4.2.11 on 2024-04-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0027_alter_profil_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('ptd_scored', models.IntegerField(default=0)),
                ('ptd_conceded', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('lose_rate', models.FloatField(default=0)),
                ('draw_rate', models.FloatField(default=0)),
                ('tournaments', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_service.stats'),
        ),
    ]
