# Generated by Django 4.2.11 on 2024-04-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0028_stats_profil_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_service.stats'),
        ),
    ]
