# Generated by Django 4.2.11 on 2024-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0029_alter_profil_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=20)),
                ('pts_scored', models.IntegerField()),
                ('pts_conceded', models.IntegerField()),
            ],
        ),
    ]
