# Generated by Django 4.2.11 on 2024-04-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0030_finishedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='auth_service.profil'),
        ),
        migrations.AddField(
            model_name='finishedgame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='auth_service.profil'),
        ),
    ]
