# Generated by Django 4.2.11 on 2024-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0032_remove_finishedgame_result_finishedgame_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedgame',
            name='pts_conceded',
        ),
        migrations.RemoveField(
            model_name='finishedgame',
            name='pts_scored',
        ),
        migrations.AddField(
            model_name='finishedgame',
            name='pts_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishedgame',
            name='pts_player2',
            field=models.IntegerField(default=0),
        ),
    ]
