# Generated by Django 4.2.11 on 2024-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0033_remove_finishedgame_pts_conceded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('do_not_disturb', 'Do not disturb'), ('inactive', 'Inactive'), ('in_game', 'Playing')], default='active', max_length=20),
        ),
    ]
