# Generated by Django 4.2.11 on 2024-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0034_alter_profil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgame',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finishedgame',
            name='give_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finishedgame',
            name='winner',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
