# Generated by Django 4.2.11 on 2024-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0034_alter_profil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='channel_name',
            field=models.CharField(default=''),
        ),
    ]
