# Generated by Django 4.2.11 on 2024-05-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0003_add_timestamps'),
        ('auth_service', '0035_profil_totp_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='totp_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='otp_totp.totpdevice'),
        ),
    ]
