# Generated by Django 4.2.11 on 2024-05-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0035_profil_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='channel_name',
        ),
    ]
