# Generated by Django 4.2.11 on 2024-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0035_finishedgame_draw_finishedgame_give_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgame',
            name='draw',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='finishedgame',
            name='give_up',
            field=models.BooleanField(),
        ),
    ]
