# Generated by Django 4.2.11 on 2024-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0036_alter_profil_totp_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='provisioning_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
