# Generated by Django 4.2.11 on 2024-05-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0036_alter_finishedgame_draw_alter_finishedgame_give_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgame',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finishedgame',
            name='give_up',
            field=models.BooleanField(default=False),
        ),
    ]
