# Generated by Django 4.2.11 on 2024-05-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0036_remove_profil_channel_name'),
        ('auth_service', '0037_profil_provisioning_uri_profil_qr_code'),
    ]

    operations = [
    ]
