# Generated by Django 4.2.11 on 2024-05-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0038_merge_20240524_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
