# Generated by Django 4.2.11 on 2024-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0039_profil_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_in_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
