# Generated by Django 4.2.11 on 2024-06-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0037_alter_finishedgame_draw_alter_finishedgame_give_up'),
        ('auth_service', '0039_profil_secret_key'),
    ]

    operations = [
    ]
