# Generated by Django 4.2.11 on 2024-06-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0040_merge_20240603_1104'),
        ('auth_service', '0040_profil_is_in_tournament'),
    ]

    operations = [
    ]
