# Generated by Django 4.2.11 on 2024-06-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0041_merge_20240603_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
