# Generated by Django 4.2.11 on 2024-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0042_alter_profil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='auth_with_42',
            field=models.BooleanField(default=False),
        ),
    ]
