# Generated by Django 4.2.11 on 2024-06-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0043_profil_auth_with_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='player_name_tour',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
