# Generated by Django 4.2.11 on 2024-06-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0043_profil_auth_with_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='friends',
            field=models.ManyToManyField(blank=True, to='auth_service.profil'),
        ),
    ]
