# Generated by Django 4.2.11 on 2024-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0043_profil_auth_with_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
