# Generated by Django 4.2.11 on 2024-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0044_profil_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='friends',
        ),
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('in_game', 'In game')], default='active', max_length=20),
        ),
    ]
