# Generated by Django 4.2.11 on 2024-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0044_profil_player_name_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
