# Generated by Django 4.2.11 on 2024-06-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0045_remove_profil_friends_alter_profil_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_receiver', to='auth_service.profil')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sender', to='auth_service.profil')),
            ],
            options={
                'unique_together': {('requester', 'receiver')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='friends',
            field=models.ManyToManyField(through='auth_service.Friend', to='auth_service.profil'),
        ),
    ]
