# Generated by Django 4.2.11 on 2024-06-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0046_remove_profil_in_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinishedGame',
        ),
    ]
