# Generated by Django 4.2.11 on 2024-06-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0044_profil_in_game'),
        ('auth_service', '0047_delete_finishedgame'),
    ]

    operations = [
    ]
