# Generated by Django 4.2.11 on 2024-06-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0047_merge_20240625_1445'),
        ('auth_service', '0048_merge_0044_profil_in_game_0047_delete_finishedgame'),
    ]

    operations = [
    ]
