# Generated by Django 4.2.11 on 2024-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0050_profil_is_in_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='goals_ratio',
            field=models.FloatField(default=0),
        ),
    ]
