# Generated by Django 4.2.11 on 2024-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0052_remove_stats_goals_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='goals_ratio',
            field=models.FloatField(default=0),
        ),
    ]
