# Generated by Django 4.2.11 on 2024-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0053_stats_goals_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='player_name_tour',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
