# Generated by Django 4.2.11 on 2024-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0002_blockedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
