# Generated by Django 5.0.4 on 2024-05-10 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0006_groupe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groupe',
            new_name='ChatGroups',
        ),
    ]
