# Generated by Django 5.0.4 on 2024-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0007_rename_groupe_chatgroups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroups',
        ),
    ]
