# Generated by Django 5.0.4 on 2024-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0009_chatgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroups',
            name='group_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
