# Generated by Django 5.0.4 on 2024-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0010_chatgroups_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroups',
            name='group_name',
        ),
    ]
