# Generated by Django 4.2.11 on 2024-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0011_remove_chatgroups_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroups',
            name='group_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
