# Generated by Django 4.2.11 on 2024-05-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0038_merge_20240524_1158'),
        ('com_service', '0013_alter_blockedusers_blocked_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_service.profil'),
        ),
    ]
