# Generated by Django 4.2.11 on 2024-06-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0014_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_service.chatgroups'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
