# Generated by Django 4.2.11 on 2024-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0015_alter_chat_room_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
