# Generated by Django 4.2.11 on 2024-06-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0016_chat_is_answered_chat_is_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_answered',
        ),
    ]
