# Generated by Django 4.2.11 on 2024-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0017_remove_chat_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
