# Generated by Django 4.2.11 on 2024-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0018_chat_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
