# Generated by Django 4.2.11 on 2024-06-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0019_chat_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='answer',
            field=models.BooleanField(null=True),
        ),
    ]
