# Generated by Django 4.2.11 on 2024-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0020_alter_chat_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_ready_button',
            field=models.BooleanField(default=False),
        ),
    ]
