# Generated by Django 4.2.11 on 2024-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0021_chat_is_ready_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_message_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='player1_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='player2_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
