# Generated by Django 4.2.11 on 2024-06-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_service', '0024_alter_match_tournament'),
        ('com_service', '0022_chat_is_message_bot_chat_player1_id_chat_player2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_service.match'),
        ),
    ]
