# Generated by Django 4.2.11 on 2024-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_service', '0023_chat_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroups',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
